Make mouse-sensitivity script more robust

diff --git a/mouse-sensitivity b/mouse-sensitivity
--- a/mouse-sensitivity
+++ b/mouse-sensitivity
@@ -1,10 +1,17 @@
 #!/bin/bash
 # Set the sensitivity for the supplied mouse
 
-mouse_name=$1
-mouse_sensitivity=3
+if [[ $# < 1 ]]; then
+    echo "Please provide device name."
+    exit 1
+else
+    mouse_name=$1
+fi
+
 if [[ $# > 1 ]]; then
     mouse_sensitivity=$2
+else
+    mouse_sensitivity=3
 fi
 
 function get_mouse_id() {
@@ -14,6 +21,22 @@ function get_mouse_id() {
     cut -c 4-
 }
 
-mouse_id=$(get_mouse_id)
+function is_number() {
+    re='^[0-9]+$'
+    if ! [[ $1 =~ $re ]] ; then
+        echo 'False'
+    else
+        echo 'True'
+    fi
+}
 
-xinput --set-prop $mouse_id 267 $mouse_sensitivity
+mouse_id=$(get_mouse_id)
+is_number=$(is_number $mouse_id)
+
+if [[ $is_number == 'True' ]]; then
+    xinput --set-prop $mouse_id 267 $mouse_sensitivity
+else
+    echo 'Device not found!'
+    exit 1
+fi
+
